version: "3"
services:
  # use mysql as the database
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    expose:
      - 3307
    volumes:
      - mysql:/var/lib/mysql

  # and get the latest wp version
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3307
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: database
    volumes:
      # - wp_data:/var/www/html
      - type: bind
        source: ./wp-content
        target: /var/www/html/wp-content
      # - ./wp-content:/var/www/html/wp-content


volumes:
  mysql:
  #wp_data:
